- name: Debug Linux configuration - start
  debug:
    msg: "--------------- Linux configuration started ---------------"

- name: Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install sshpass
  ansible.builtin.package:
    name: 
      - sshpass
      - fontconfig
    state: present

- name: Change instance timezone
  ansible.builtin.command: timedatectl set-timezone America/Sao_Paulo
  become: true

- name: This command will install jfrog cli
  ansible.builtin.get_url:
    url: https://install-cli.jfrog.io
    dest: "{{ jfrog_installer }}"
    mode: '0755'

- name: Set vault token
  set_fact:
    artifactory_access_token: "{{ lookup('community.hashi_vault.hashi_vault', 'url=' ~ vault_url ~ ' secret=' ~ artifactory_reader_token_path ~ ':access_token') }}"

- name: Fetch OpenJDK Corretto 22 from jfrog
  ansible.builtin.get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/{{ corretto_pkg }}"
    headers:
      Authorization: "Bearer {{ artifactory_access_token }}"
    dest: "/tmp/{{ corretto_pkg }}"
    validate_certs: true


- name: Install OpenJDK Corretto 22
  ansible.builtin.yum:
    name: "/tmp/{{ corretto_pkg }}"
    state: present
    disable_gpg_check: true
  become: true

- name: Fetch the Apache Tomcat installer
  ansible.builtin.get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    headers:
      Authorization: "Bearer {{ artifactory_access_token }}"
    dest: "{{ tomcat_archive }}"
    validate_certs: true
  become: true

- name: Unzip Tomcat 10
  ansible.builtin.unarchive:
    src: "{{ tomcat_archive }}"
    dest: /opt
    remote_src: yes
  become: true

- name: Rename Tomcat folder
  shell: | 
   [ -d /opt/tomcat10 ] || mv /opt/apache-tomcat-{{ tomcat_version }} /opt/tomcat10
  become: true

- name: Create Tomcat user
  ansible.builtin.user:
    name: tomcat
    shell: /sbin/nologin
    create_home: false
    state: present

- name: Copy tomcat users file
  copy:
    src: ./files/tomcat-users.xml.j2
    dest: /opt/tomcat10/conf/tomcat-users.xml
    mode: 0755
    force: false
  become: true

- name: Install LPFat application fonts
  ansible.builtin.get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/LPFat/lpfat_fonts.zip"
    headers:
      Authorization: "Bearer {{ artifactory_access_token }}"
    dest: "/tmp/lpfat_fonts.zip"
    validate_certs: true

- name: Create folder for the application fonts
  file:
    path: /opt/tomcat10/fonts/
    state: directory
  become: true

- name: Unzip fonts file
  unarchive:
    src: /tmp/lpfat_fonts.zip
    dest: /opt/tomcat10/fonts/
    remote_src: yes
  become: true

- name: Create symbolic links for the tomcat scripts
  shell: | 
    [ -L /bin/tomcatup ] || ln -s /opt/tomcat10/bin/startup.sh /bin/tomcatup ; [ -L /bin/tomcatdown ] || ln -s /opt/tomcat10/bin/shutdown.sh /bin/tomcatdown
  args:
    chdir: /opt/tomcat10
  become: true    

- name: Stop tomcat
  shell: | 
    tomcatdown
  become: true
  become_user: tomcat
  ignore_errors: true
  
- name: Cleanup the tomcat and the temp folders
  shell: |
    rm -rf /opt/tomcat10/webapps/*.war /opt/tomcat10/webapps/LpFat_* /tmp/*.war
  become: true


- name: Download war files from the vendor SFTP server
  shell: |
    url=$(aws secretsmanager get-secret-value --region sa-east-1 --secret-id {{ secret_id }} | jq -r '.SecretString' | jq -r '.url' )
    port=$(aws secretsmanager get-secret-value --region sa-east-1 --secret-id {{ secret_id }} | jq -r '.SecretString' | jq -r '.port' )
    username=$(aws secretsmanager get-secret-value --region sa-east-1 --secret-id {{ secret_id }} | jq -r '.SecretString' | jq -r '.username' )
    password=$(aws secretsmanager get-secret-value --region sa-east-1 --secret-id {{ secret_id }} | jq -r '.SecretString' | jq -r '.password' )
    SSHPASS=${password} sshpass -e sftp -o StrictHostKeyChecking=accept-new -P ${port} ${username}@${url} << ENDSFTP
    cd releases/{{ env_dir }}/
    get *.war
    quit
    ENDSFTP
  args:
    chdir: /tmp/
  failed_when: false  

- name: Copy downloaded war files to the tomcat folder, if the files are new
  shell: |
    cp -u /tmp/*.war /opt/tomcat10/webapps/
  become: true
  failed_when: false

- name: Set LpFat S3 environment variables
  lineinfile:
    path: "/etc/environment"
    state: present
    line: "STORAGE_AWSS3_USE_IAM=true"
  become: true

- name: Change tomcat folder ownership
  file:
    path: /opt/tomcat10
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Start tomcat
  shell: | 
    /opt/tomcat10/bin/startup.sh
  become: true
  become_user: tomcat

- name: Create a shell script from the user-data.txt file
  shell: |
    cp /var/lib/cloud/instance/user-data.txt /tmp/user-data.sh && chmod +x /tmp/user-data.sh
  become: true

- name: Install CIFS utilities
  ansible.builtin.package:
    name: cifs-utils
    state: present
  become: true

- name: Create Samba credentials directory
  ansible.builtin.file:
    path: /etc/samba
    state: directory
    mode: '0755'
  become: true

- name: Get credencials SMB AWS Secrets Manager
  shell: |
    aws secretsmanager get-secret-value \
      --region {{ aws_region }} \
      --secret-id {{ secret_smb }} \
      --query SecretString \
      --output text
  register: smb_secret_raw
  no_log: true
  become: true

- name: Parse credencials SMB
  set_fact:
    smb_credentials: "{{ smb_secret_raw.stdout | from_json }}"
  no_log: true

- name: Create CIFS credentials file
  ansible.builtin.copy:
    content: |
      username={{ smb_credentials.username }}
      password={{ smb_credentials.password }}
      domain=WORKGROUP
    dest: /etc/samba/cred_lpfat
    mode: '0600'
    owner: root
    group: root
  become: true

- name: Create mount points
  ansible.builtin.file:
    path: "/mnt/bradesco/{{ item | lower }}"
    state: directory
    mode: '0755'
  become: true
  loop: [ "ENTRADA", "SAIDA" ]

- name: Find IP Windows in inventory
  set_fact:
    win_ip: "{{ hostvars[groups['tag_leaseplan_os_type_windows'][0]]['ec2_private_ip_address'] | default(hostvars[groups['tag_leaseplan_os_type_windows'][0]]['private_ip_address']) | default(hostvars[groups['tag_leaseplan_os_type_windows'][0]]['ansible_host']) }}"
  when: groups['tag_leaseplan_os_type_windows'] is defined

- name: Ensure CIFS share mounted
  mount:
    src: "//{{ win_ip }}/{{ item }}"
    path: "/mnt/bradesco/{{ item | lower }}"
    fstype: cifs
    opts: "vers=3.1.1,credentials=/etc/samba/cred_lpfat,uid=1000,gid=1000"
    state: mounted
  loop: [ "ENTRADA", "SAIDA" ]

#- name: Create cron job for the AWX rerun
#  cron:
#    name: "Run the user-data script every hour"
#    weekday: "*"
#    minute: "30"
#    hour: "*"
#    job: "/tmp/user-data.sh > /dev/null"
#    state: present
#  become: true

- name: Copy LPFat scheduler script
  copy:
    src: ./files/lpfat_scheduler.sh
    dest: /tmp/lpfat_scheduler.sh
    mode: 0755
    force: false
  become: true




#- name: Create cron job for the LPFat application scheduler
#  cron:
#    name: "Run the LPFat scheduler script every minute"
#    weekday: "*"
#    minute: "1"
#    hour: "*"
#    job: "/tmp/lpfat_scheduler.sh > /tmp/lpfat_scheduler.log"
#    state: present
#  become: true