- name: Debug Linux configuration - start
  debug:
    msg: "--------------- Linux configuration started ---------------"

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
  ignore_errors: true
  become: true

- name: This command will install jfrog cli
  shell: |
    curl -fL https://install-cli.jfrog.io | sh
  args:
    chdir: /var/tmp
  become: true
  become_user: root

- name: Fetch OpenJDK Corretto 22 from jfrog
  get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/java-22-amazon-corretto-devel-22.0.2.9-1.x86_64.rpm"
    url_username: "art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default"
    url_password: "{{ lookup('hashi_vault', 'secret=artifactory/token/art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default:access_token url={{ vault_url }}') }}"
    dest: /tmp/java-22-amazon-corretto-devel-22.0.2.9-1.x86_64.rpm


- name: Install OpenJDK Corretto 22
  yum:
    name: /tmp/java-22-amazon-corretto-devel-22.0.2.9-1.x86_64.rpm
    state: present
    disable_gpg_check: true
  become: true

- name: Fetch the Apache Tomcat installer
  get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/apache-tomcat-10.1.30.tar.gz"
    url_username: "art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default"
    url_password: "{{ lookup('hashi_vault', 'secret=artifactory/token/art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default:access_token url={{ vault_url }}') }}"
    dest: /opt/apache-tomcat-10.1.30.tar.gz
  become: true

- name: Unzip Tomcat 10
  unarchive:
    src: /opt/apache-tomcat-10.1.30.tar.gz
    dest: /opt
    remote_src: yes
  become: true

- name: Rename Tomcat folder
  command: mv /opt/apache-tomcat-10.1.30 /opt/tomcat10
  become: true

- name: Create Tomcat user
  user:
    name: tomcat
    shell: /bin/bash
    create_home: no
  become: true

- name: Copy tomcat users file
  copy:
    src: ./files/tomcat-users.xml.j2
    dest: /opt/tomcat10/conf/tomcat-users.xml
    mode: 0755
  become: true

- name: Change tomcat folder ownership
  file:
    path: /opt/tomcat10
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Create symbolic links for the tomcat scripts
  shell: | 
    ln -s /opt/tomcat10/bin/startup.sh /bin/tomcatup ; ln -s /opt/tomcat10/bin/shutdown.sh /bin/tomcatdown
  args:
    chdir: /opt/tomcat10
  become: true    

- name: Fetch the LPFat war file
  get_url:
    url: "{{ artifactory_url }}/{{ wkl_virt_repo_name }}/LPFat/development/LpFat_EmTestes_20241003164125.war"
    url_username: "art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default"
    url_password: "{{ lookup('hashi_vault', 'secret=artifactory/token/art-{{ workload_name.split(\"-\")[0] }}-read-generic-local-default:access_token url={{ vault_url }}') }}"
    dest: '/opt/tomcat10/webapps/LeaseFat.war'
  become: true

- name: Set LpFat S3 environment variables
  lineinfile:
    path: "/etc/environment"
    state: present
    line: "STORAGE_AWSS3_USE_IAM=true"
  become: true

- name: Start tomcat
  shell: | 
    tomcatup
  become: true

- name: Copy the CloudServices config file to the server
  copy:
    src: ./files/CloudServices.config
    dest: /opt/tomcat10/webapps/LeaseFat/WEB-INF/CloudServices.config
    mode: 0755
  become: true

- name: Get Secret Manager credentials and update cluster_config.json
  shell: |
    LPFAT_BUCKET="lpfat-d-596599667803"
    sed -i "s/%%%LPFAT_BUCKET_NAME%%%/$LPFAT_BUCKET/g" /opt/tomcat10/webapps/LeaseFat/WEB-INF/CloudServices.config
  become: true