---
# here some exampels on how to join the domain by using a role and how to setup rdp access.
# - name: join the domain
#   include_role:
#     name: 'domain_join'

- name: set remote desktop users
  ansible.windows.win_group_membership:
    name: remote desktop users
    members: "{{ remote_desktop_users }}"
    state: present

- name: set local admins
  ansible.windows.win_group_membership:
    name: administrators
    members: "{{ local_administrators }}"
    state: present

- name: Create Windows user for SMB authentication
  ansible.windows.win_user:
    name: LpFATUser
    password: "{{ lpfat_user_password }}"
    password_never_expires: yes
    state: present
    groups:
      - Users

- name: Set permissions on directories
  ansible.windows.win_acl:
    path: C:\STCPCLT_BRADESCO\O0055BRADESCO\{{ item }}
    user: LpFATUser
    rights: FullControl
    type: allow
    state: present
  loop: [ "ENTRADA", "SAIDA" ]

- name: Create SMB shares
  ansible.windows.win_share:
    path: C:\STCPCLT_BRADESCO\O0055BRADESCO\{{ item }}
    name: "{{ item }}"
    full: LpFATUser
  loop: [ "ENTRADA", "SAIDA" ]




# - name: Download the Scopus tool installer
