---
# here some exampels on how to join the domain by using a role and how to setup rdp access.
- name: join the domain
  include_role:
    name: 'domain_join'

# - name: set remote desktop users
#   win_group_membership:
#     name: remote desktop users
#     members: "{{ remote_desktop_users }}"
#     state: present

# - name: set local admins
#   win_group_membership:
#     name: administrators
#     members: "{{ local_administrators }}"
#     state: present

- name: Create SMB shares
  win_share:
    path: C:\STCPCLT_BRADESCO\O0055BRADESCO\{{ item }}
    name: "{{ item }}"
    full: LpFATUser
  loop:
    - ENTRADA
    - SAIDA



# - name: Download the Scopus tool installer
