{
  "name": "0072-wkl-d-lpbr-apps-lpfat-linux",
  "description": "0072-wkl-d-lpbr-apps-lpfat",
  "job_type": "run",
  "inventory": "0072-wkl-d-lpbr-apps-lpfat-2073",
  "project": "0072-wkl-lpbr-apps-lpfat-3869",
  "playbook": "callback.yml",
  "scm_branch": "WLDOPT-2515-lpfat-development",
  "forks": 0,
  "limit": "",
  "verbosity": 0,
  "extra_vars": "{\"instance_id\": \"i-04b6025e279b53acd\", \"target\": \"ec2-0072-d-sae1-lpfat-lp\", \"tasks\": [\"install_lpfat_tools\"]}",
  "job_tags": "",
  "force_handlers": false,
  "skip_tags": "",
  "start_at_task": "",
  "timeout": 0,
  "use_fact_cache": false,
  "execution_environment": "LeasePlan LZ Default Execution Environment (ansible core v2.12)-1",
  "job_template": "0072-wkl-d-lpbr-apps-lpfat-linux-4373",
  "allow_simultaneous": false,
  "instance_group": null,
  "diff_mode": true,
  "job_slice_number": 0,
  "job_slice_count": 1,
  "webhook_service": "",
  "webhook_credential": null,
  "webhook_guid": "",
  "id": 996691,
  "credentials": [
    "0072-d-aws-ssm (1568)",
    "0072-d-vault-token (1567)"
  ],
  "labels": []
}
