---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: chatbot-blip-envio-nps
  namespace: chatbot
spec: 
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers:
            - env:
                - name: APPLICATION_PORT
                  value: "8080"
                - name: CHATBOT_URL
                  valueFrom:
                    secretKeyRef:
                      key: blip-chatbot-url
                      name: blip-chatbot
                - name: CHATBOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: blip-chatbot-username
                      name: blip-chatbot
                - name: CHATBOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: blip-chatbot-password
                      name: blip-chatbot
                - name: CHATBOT_KEY
                  valueFrom:
                    secretKeyRef:
                      key: blip-chatbot-key
                      name: blip-chatbot
                - name: AWS_SQS_QUEUE_BLIP_NPS
                  value: "https://sqs.sa-east-1.amazonaws.com/847447826148/sqs-0072-a-sae1-std-chatbot-nps"
                - name: EVENT_URI
                  value: "http://event-log-event.event-log:8080/service/event/v1/log/criar"
              name: chatbot-blip-envio-nps
              image: 'cr.core-services.leaseplan.systems/0072/chatbot-blip-envio-nps:RELEASE-2.0.x9'
              ports:
              - containerPort: 8080
              resources:
                limits:
                  memory: "300Mi"
                  cpu: "100m"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
          serviceAccount: lpbr-sqs
          serviceAccountName: lpbr-sqs
          imagePullSecrets:
            - name: harbor-docker-creds
          restartPolicy: Never